### ISSUE TITLE
CI Hygiene: rustsec/audit-check compiles cargo-audit from source and now fails on tinyvec 1.13.0

### ISSUE THREAD

**Issue by lexoliu** [water-rs/waterui#316]
The Hygiene job's "Security audit" step (`rustsec/audit-check@v2`) fails on every PR since today (first seen on #315, run job "Hygiene"):

```
error: cannot find macro `vec` in this scope
error: could not compile `tinyvec` (lib) due to 1 previous error
error: failed to compile `cargo-audit v0.22.2`
```

`audit-check` builds `cargo-audit` from source with a fresh resolution on every run, so a freshly published broken dependency (tinyvec 1.13.0, which does not compile on stable 1.98 — the same regression as #312) breaks our gate without any change on our side. The rest of the Hygiene job already uses `taiki-e/install-action` for `cargo-deny`, which downloads a prebuilt binary.

Fix: install `cargo-audit` the same way (`taiki-e/install-action@cargo-audit`) and run `cargo audit` directly. Coverage is unchanged — same tool, same advisory database — the tool's own build just stops being part of our critical path.
