### PR TITLE
fix(cli): seed the managed FFI crate's Cargo.lock from the project lockfile

### LINKED ISSUE #312: water run: the generated FFI crate resolves its own Cargo.lock instead of the project's, so a fresh registry publish can break the app build
## Problem

`water run` builds an application through the generated FFI crate under `~/.water/build_cache/<project>/managed_backends/ffi/`. That crate has its own `Cargo.lock`, resolved fresh from the registry the first time it is generated, so the dependency set the app is built with is not the one the project (or, for workspace members, the workspace) pins and tests.

Observed today on `examples/map`: the workspace `Cargo.lock` pins `tinyvec 1.12.0`, `examples/image`'s managed crate (generated earlier) also has 1.12.0, but `examples/map`'s managed crate resolved `tinyvec 1.13.0` — published since — which does not compile on stable 1.98:

```
error: cannot find macro `vec` in this scope
 --> tinyvec-1.13.0/src/tinyvec.rs
note: `vec` is imported here, but it is a module, not a macro
  3 | use alloc::vec::{self, Vec};
```

so `water run --platform macos` fails in a dependency that CI never sees, while every workspace check is green. Any freshly published dependency with a regression can break `water run` this way, and two examples in the same workspace build different dependency versions.

## Expected

The managed FFI crate resolves against the project's lockfile: when the project is a workspace member, the workspace `Cargo.lock`; otherwise the project's own `Cargo.lock`. Regenerating the managed crate must not re-resolve versions the project already pins. (`cargo`'s `--locked`/copying the lockfile into the generated crate before the first resolve are the obvious mechanisms; `cargo` will keep the pinned versions and only add entries for crates the lockfile does not know.)

Found while verifying #173. The tinyvec 1.13.0 upstream regression is separate from this lockfile-isolation defect.

### PR DESCRIPTION
**Pull request by lexoliu**
The managed FFI crate under `~/.water/build_cache/…/managed_backends/ffi` is its own Cargo workspace and resolved its graph fresh from the registry, so `water run` built the app with versions nothing in the project pins or tests; `examples/map` picked up `tinyvec 1.13.0` that way and failed to compile while every workspace check was green (#312).

- `Project` resolves the workspace root alongside the target directory from the single `cargo metadata --no-deps` run it already makes (`CargoLayout`), and exposes `lockfile_path()`: the workspace `Cargo.lock` for a member, the project's own otherwise.
- `templates::ffi::seed_lockfile` copies that lockfile into the managed crate before Cargo resolves. Cargo keeps every pinned version and only adds the FFI-only entries on top. A copy of the seed (`Cargo.lock.seed`) sits beside the managed lockfile so re-seeding happens only when the project's pins change or the managed lockfile is missing — never on every scaffold, which would re-resolve the FFI-only entries (and hit the index) each run. A project with no lockfile yet is left to resolve on its own.
- Unit test covers first seed, Cargo's rewrite being left alone, re-seed on changed pins, and re-seed after deletion.

Verified end to end on `examples/map` with the managed `Cargo.lock` deleted: the CLI wrote the 353 KB workspace lockfile in as the seed, Cargo pruned it to the 211 KB the FFI graph needs, and the managed lockfile carries `tinyvec 1.12.0` (the workspace pin) instead of a fresh resolution.

Fixes #312

### CODE REVIEW

**Comment by lexoliu** [comment]
End-to-end run completed: with the apple-backend fix from water-rs/apple-backend#13 checked out, `water run --platform macos` on `examples/map` seeded the managed lockfile, built, and reached `Application started` (Metal adapter selected, GPU surface attached). The first two attempts failed in the Swift package for the unrelated #343 regression, which is what surfaced that issue.
