### ISSUE TITLE
water run: the generated FFI crate resolves its own Cargo.lock instead of the project's, so a fresh registry publish can break the app build

### ISSUE THREAD

**Issue by lexoliu** [water-rs/waterui#312]
## Problem

`water run` builds an application through the generated FFI crate under `~/.water/build_cache/<project>/managed_backends/ffi/`. That crate has its own `Cargo.lock`, resolved fresh from the registry the first time it is generated, so the dependency set the app is built with is not the one the project (or, for workspace members, the workspace) pins and tests.

Observed today on `examples/map`: the workspace `Cargo.lock` pins `tinyvec 1.12.0`, `examples/image`'s managed crate (generated earlier) also has 1.12.0, but `examples/map`'s managed crate resolved `tinyvec 1.13.0` — published since — which does not compile on stable 1.98:

```
error: cannot find macro `vec` in this scope
 --> tinyvec-1.13.0/src/tinyvec.rs
note: `vec` is imported here, but it is a module, not a macro
  3 | use alloc::vec::{self, Vec};
```

so `water run --platform macos` fails in a dependency that CI never sees, while every workspace check is green. Any freshly published dependency with a regression can break `water run` this way, and two examples in the same workspace build different dependency versions.

## Expected

The managed FFI crate resolves against the project's lockfile: when the project is a workspace member, the workspace `Cargo.lock`; otherwise the project's own `Cargo.lock`. Regenerating the managed crate must not re-resolve versions the project already pins. (`cargo`'s `--locked`/copying the lockfile into the generated crate before the first resolve are the obvious mechanisms; `cargo` will keep the pinned versions and only add entries for crates the lockfile does not know.)

Found while verifying #173. The tinyvec 1.13.0 upstream regression is separate from this lockfile-isolation defect.

**Comment by lexoliu** [comment]
Same failure on the Hydrolysis path: `water run --platform macos --backend hydrolysis` for `examples/map` builds its own managed hydrolysis crate, which also resolved `tinyvec 1.13.0` and fails to compile, while the workspace lock pins 1.12.0. Both managed crates (ffi and hydrolysis) need to resolve against the project's lockfile.
